---
# Install file synchronization tools

- name: Install Syncthing
  block:
    - name: Ensure keyrings directory exists
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'
      become: yes

    - name: Download Syncthing GPG key
      ansible.builtin.get_url:
        url: https://syncthing.net/release-key.gpg
        dest: /etc/apt/keyrings/syncthing.gpg
        mode: '0644'
      become: yes

    - name: Add Syncthing repository
      apt_repository:
        repo: "deb [signed-by=/etc/apt/keyrings/syncthing.gpg] https://apt.syncthing.net/ syncthing stable"
        state: present
        filename: syncthing
      become: yes

    - name: Install Syncthing and GUI
      ansible.builtin.apt:
        name:
          - syncthing
          - syncthing-gtk
        state: present
        update_cache: yes
      become: yes

    - name: Check if Syncthing is installed
      ansible.builtin.command: dpkg -l syncthing
      register: syncthing_check
      changed_when: false
      failed_when: false

    - name: Enable Syncthing service for user
      ansible.builtin.systemd:
        name: "syncthing@{{ primary_user }}"
        enabled: yes
        state: started
        daemon_reload: yes
      become: yes
      when: syncthing_check.rc == 0
  when: "'syncthing' in devtools_sync_tools"

- name: Install Resilio Sync
  block:
    - name: Ensure keyrings directory exists
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'
      become: yes

    - name: Download Resilio Sync GPG key
      ansible.builtin.get_url:
        url: https://linux-packages.resilio.com/resilio-sync/key.asc
        dest: /etc/apt/keyrings/resilio-sync.asc
        mode: '0644'
      become: yes

    - name: Add Resilio Sync repository
      apt_repository:
        repo: "deb [signed-by=/etc/apt/keyrings/resilio-sync.asc] http://linux-packages.resilio.com/resilio-sync/deb resilio-sync non-free"
        state: present
        filename: resilio-sync
      become: yes

    - name: Install Resilio Sync
      ansible.builtin.apt:
        name: resilio-sync
        state: present
        update_cache: yes
      become: yes
  when: "'resilio-sync' in devtools_sync_tools"

- name: Install FreeFileSync
  block:
    - name: Download FreeFileSync
      ansible.builtin.get_url:
        url: https://freefilesync.org/download/FreeFileSync_13.3_Linux.tar.gz
        dest: /tmp/freefilesync.tar.gz
        mode: '0644'
      become: yes

    - name: Extract FreeFileSync
      ansible.builtin.unarchive:
        src: /tmp/freefilesync.tar.gz
        dest: /opt/
        creates: /opt/FreeFileSync
        remote_src: yes
      become: yes

    - name: Create FreeFileSync desktop entry
      ansible.builtin.template:
        src: freefilesync.desktop.j2
        dest: /usr/share/applications/freefilesync.desktop
        mode: '0644'
      become: yes
  when: "'freefilesync' in devtools_sync_tools"

- name: Install Nextcloud desktop client
  block:
    - name: Add Nextcloud PPA
      apt_repository:
        repo: "ppa:nextcloud-devs/client"
        state: present
      become: yes

    - name: Install Nextcloud client
      ansible.builtin.apt:
        name: nextcloud-desktop
        state: present
        update_cache: yes
      become: yes
  when: "'nextcloud-client' in devtools_sync_tools"

- name: Install Rclone and GUI
  block:
    - name: Install Rclone
      ansible.builtin.shell: |
        curl https://rclone.org/install.sh | sudo bash
      become: yes
      args:
        creates: /usr/bin/rclone

    - name: Get latest Rclone Browser release
      ansible.builtin.uri:
        url: https://api.github.com/repos/kapitainsky/RcloneBrowser/releases/latest
        timeout: 10
      register: rclone_browser_release
      failed_when: false

    - name: Install Rclone Browser AppImage
      ansible.builtin.get_url:
        url: >
          {{ rclone_browser_release.json.assets |
             selectattr('name', 'match', '.*linux.*x86_64.*AppImage$') |
             map(attribute='browser_download_url') | first | default('') }}
        dest: "/home/{{ primary_user }}/.local/bin/rclone-browser.AppImage"
        mode: '0755'
      become: yes
      become_user: "{{ primary_user }}"
      when: 
        - rclone_browser_release is succeeded
        - rclone_browser_release.json.assets | selectattr('name', 'match', '.*linux.*x86_64.*AppImage$') | list | length > 0

    - name: Create Rclone Browser desktop entry
      ansible.builtin.copy:
        content: |
          [Desktop Entry]
          Version=1.0
          Type=Application
          Name=Rclone Browser
          Comment=GUI for rclone
          Icon=folder-remote
          Exec={{ ansible_env.HOME }}/.local/bin/rclone-browser.AppImage
          Categories=Network;FileTransfer;
          Terminal=false
        dest: "/home/{{ primary_user }}/.local/share/applications/rclone-browser.desktop"
        owner: "{{ primary_user }}"
        group: "{{ primary_user }}"
        mode: '0644'
      become: yes
      when: 
        - rclone_browser_release is succeeded
        - rclone_browser_release.json.assets | selectattr('name', 'match', '.*linux.*x86_64.*AppImage$') | list | length > 0
  when: "'rclone' in devtools_sync_tools"

- name: Install Grsync (rsync GUI)
  ansible.builtin.apt:
    name: grsync
    state: present
  become: yes
  when: "'grsync' in devtools_sync_tools"
