---
galaxy_info:
  author: Ubuntu Bootstrap
  description: Role for managing user dotfiles and configurations
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - focal    # 20.04
        - jammy    # 22.04
        - noble    # 24.04

dependencies: []
