configurable_items:
  custom-accent:
    id: custom-accent
    value: '#89b4fa'
  custom-background:
    id: custom-background
    value: '#1e1e2e'
  custom-foreground:
    id: custom-foreground
    value: '#cdd6f4'
  editor-font-family:
    id: editor-font-family
    value: JetBrains Mono
  editor-line-height:
    id: editor-line-height
    value: 1.5
  swappiness:
    id: swappiness
    value: 10
  terminal-bell:
    id: terminal-bell
    value: Visual
  terminal-blur:
    id: terminal-blur
    value: 5
  terminal-cursor-style:
    id: terminal-cursor-style
    value: Block
  terminal-font-family:
    id: terminal-font-family
    value: JetBrains Mono
  terminal-font-size:
    id: terminal-font-size
    value: 12
  terminal-padding:
    id: terminal-padding
    value: 8
  terminal-scrollback:
    id: terminal-scrollback
    value: 10000
  terminal-transparency:
    id: terminal-transparency
    value: 85
  theme-terminal-opacity:
    id: theme-terminal-opacity
    value: 90
  theme-ui-scale:
    id: theme-ui-scale
    value: '1.00'
  vscode-font-size:
    id: vscode-font-size
    value: 14
  vscode-tab-size:
    id: vscode-tab-size
    value: 4
metadata:
  created_by: ubootu_unified_tui
  version: '1.0'
selected_items:
- dev-python
- python
- dev-javascript
- nodejs
- dev-code-editors
- vscode
- dev-vcs
- git
- dev-containers
- docker
- dev-shells
- bash
- dev-editor-settings
- vscode-sticky-scroll
- app-theme-integration
- editor-minimap
- editor-ligatures
- vscode-bracket-colorization
- dev-terminal-settings
- terminal-cursor-blink
- desktop
- gnome
- web-browsers
- firefox
- vivaldi
- text-editors-ides
- vscode
- video-streaming
- vlc
- productivity-office
- libreoffice
- security
- ufw
- theme-settings
- theme-sync-apps
- system
- enable-trim
- gaming
- gamemode
- applications
- timeshift
