configurable_items:
  custom-accent:
    id: custom-accent
    value: '#89b4fa'
  custom-background:
    id: custom-background
    value: '#1e1e2e'
  custom-foreground:
    id: custom-foreground
    value: '#cdd6f4'
  editor-font-family:
    id: editor-font-family
    value: Fira Code
  editor-line-height:
    id: editor-line-height
    value: 1.5
  swappiness:
    id: swappiness
    value: 10
  terminal-bell:
    id: terminal-bell
    value: Visual
  terminal-blur:
    id: terminal-blur
    value: 5
  terminal-cursor-style:
    id: terminal-cursor-style
    value: Block
  terminal-font-family:
    id: terminal-font-family
    value: Fira Code
  terminal-font-size:
    id: terminal-font-size
    value: 12
  terminal-padding:
    id: terminal-padding
    value: 8
  terminal-scrollback:
    id: terminal-scrollback
    value: 10000
  terminal-transparency:
    id: terminal-transparency
    value: 85
  theme-terminal-opacity:
    id: theme-terminal-opacity
    value: 90
  theme-ui-scale:
    id: theme-ui-scale
    value: '1.00'
  vscode-font-size:
    id: vscode-font-size
    value: 14
  vscode-tab-size:
    id: vscode-tab-size
    value: 4
metadata:
  created_by: ubootu_unified_tui
  version: '1.0'
selected_items:
- dev-code-editors
- vscode
- cursor
- dev-vcs
- git
- git-config-global
- dev-shells
- bash
- dev-editor-settings
- editor-ligatures
- vscode-bracket-colorization
- vscode-theme-sync
- vscode-sticky-scroll
- app-theme-integration
- editor-minimap
- vscode-inlay-hints
- cursor
- dev-terminal-settings
- terminal-cursor-blink
- desktop
- gnome
- web-browsers
- vivaldi
- firefox
- text-editors-ides
- vscode
- video-streaming
- vlc
- security
- ufw
- fail2ban
- theme-settings
- theme-auto-switch
- theme-sync-apps
- system
- enable-trim
- gaming
- wine
- gamemode
- discord
- applications
- gparted
- caffeine
- copyq
- redshift
- peek
- etcher
- timeshift
- ventoy
- flameshot
- dev-go
- go
- gofmt
- dev-python
- pyenv
- pytest
- pipenv
- black
- poetry
- python
- dev-javascript
- nodejs
- nvm
- prettier
- eslint
- yarn
- bundler
- mocha
- pnpm
- jest
- dev-rust
- rustup
- rustfmt
- cargo
- rust
- dev-java
- java
- dev-cpp
- cmake
- dev-other-langs
- ruby
- php
- dev-text-editors
- vim
- neovim
- dev-containers
- docker-compose
- kubernetes
- docker
- dev-sql-databases
- postgresql
- dev-nosql-databases
- mongodb
- elasticsearch
- redis
- dev-db-tools
- pgadmin
- dbeaver
- dev-api-tools
- httpie
- postman
- insomnia
- dev-cloud
- aws-cli
- terraform
- pulumi
- dev-build-tools
- make
- dev-documentation
- mkdocs
- dev-utilities
- perf
- gnu-global
- ltrace
- wine
- binutils
- gdb
- strace
- ansible-cloud
- heaptrack
- jq
- ctags
- valgrind
- yq
- ai-ml
- ollama
- pytorch
- jupyter
- tensorflow
- anaconda
- customization
- chezmoi
- conky
- ulauncher
- dotfiles-manager
- yadm
- gnome-tweaks
- albert
- theme-universal
- theme-solarized-dark
- theme-solarized-light
- theme-catppuccin-frappe
- theme-catppuccin-macchiato
- theme-dracula
- theme-nord
- theme-ayu-dark
- theme-one-dark
- theme-tokyo-night-storm
- theme-monokai
- theme-everforest
- theme-tokyo-night
- theme-catppuccin-latte
- theme-gruvbox-dark
- theme-gruvbox-light
- theme-catppuccin-mocha
- theme-material
- theme-tokyo-night-light
- networking
- vnstat
- ethtool
- netcat
- nmap
- wireshark
- nethogs
- mtr
- iperf3
- tcpdump
- iftop
- virtualization
- vagrant
- virtualbox
- cloud-tools
- aws-cli
- kubectl
- ansible-cloud
- terraform
- helm
- security-testing
- john
- mat2
- crackmap-exec
- burp-suite
- wifite
- tcpdump
- reaver
- aircrack-ng
- anonsurf
- rkhunter
- onionshare
- chkrootkit
- nikto
- netcat
- binwalk
- volatility
- nmap
- hydra
- wireshark
- kismet
- lynis
- dirbuster
- openvas
- foremost
- hashcat
- masscan
- autopsy
- tor-browser
- proxychains
- sqlmap
- kloak
- owasp-zap
- tails-installer
- bleachbit
- graphics-media
- gimp
- productivity-office
- teams
- thunderbird
- communication
- zoom
- teams
- signal
- discord
- audio-music
- spotify
- file-management
- midnight-commander
- system-tools
- gparted
- stacer
- synaptic
- timeshift
- bleachbit
