configurable_items: {}
metadata:
  created_by: ubootu_unified_tui
  version: '1.0'
selected_items:
- python
- git
- development
- nodejs
- docker-compose
- rust
- go
- docker
- python
- git
- neovim
- vim
- vscode
- ai-ml
- jupyter-lab
- pytorch
- ollama
- text-generation-webui
- tensorflow
- pytorch
- desktop
- hyprland
- gnome
- applications
- vlc
- brave
- thunderbird
- spotify
- security
- ufw
- fail2ban
- veracrypt
- keepassxc
- system
- enable-snap
- enable-flatpak
- swappiness
