---
# Install password managers

- name: Install KeePassXC
  ansible.builtin.apt:
    name: keepassxc
    state: present
  become: yes
  when: "'keepassxc' in password_managers"

- name: Install Bitwarden
  snap:
    name: bitwarden
    state: present
  become: yes
  when: "'bitwarden' in password_managers and enable_snap | default(true)"

- name: Install 1Password
  block:
    - name: Add 1Password GPG key
      apt_key:
        url: https://downloads.1password.com/linux/keys/1password.asc
        state: present
      become: yes

    - name: Add 1Password repository
      apt_repository:
        repo: "deb [arch=amd64] https://downloads.1password.com/linux/debian/amd64 stable main"
        state: present
        filename: 1password
      become: yes

    - name: Install 1Password
      ansible.builtin.apt:
        name: 1password
        state: present
        update_cache: yes
      become: yes
  when: "'1password' in password_managers"

- name: Install Enpass
  block:
    - name: Add Enpass repository key
      apt_key:
        url: https://apt.enpass.io/keys/enpass-linux.key
        state: present
      become: yes

    - name: Add Enpass repository
      apt_repository:
        repo: "deb https://apt.enpass.io/ stable main"
        state: present
        filename: enpass
      become: yes

    - name: Install Enpass
      ansible.builtin.apt:
        name: enpass
        state: present
        update_cache: yes
      become: yes
  when: "'enpass' in password_managers"

- name: Install pass (command-line password manager)
  ansible.builtin.apt:
    name:
      - pass
      - pass-extension-otp
    state: present
  become: yes
  when: "'pass' in password_managers"

# Install browser extensions for password managers
- name: Create directory for browser extension configs
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config/browser-extensions"
    state: directory
    mode: '0755'
  when: password_managers | length > 0

- name: Create browser extension recommendation file
  ansible.builtin.copy:
    dest: "{{ ansible_env.HOME }}/.config/browser-extensions/password-managers.txt"
    content: |
      Recommended browser extensions for your password managers:

      {% if 'keepassxc' in password_managers %}
      KeePassXC:
      - KeePassXC-Browser extension
      - Available for Chrome, Firefox, Edge, and other browsers
      {% endif %}

      {% if 'bitwarden' in password_managers %}
      Bitwarden:
      - Official Bitwarden browser extension
      - Available for all major browsers
      {% endif %}

      {% if '1password' in password_managers %}
      1Password:
      - 1Password browser extension
      - Available for all major browsers
      {% endif %}

      {% if 'enpass' in password_managers %}
      Enpass:
      - Enpass browser extension
      - Available for Chrome, Firefox, Edge, Safari
      {% endif %}
    mode: '0644'
  when: password_managers | length > 0
