---
- name: Install XFCE desktop environment
  ansible.builtin.apt:
    name: "{{ de_packages.xfce }}"
    state: present
    install_recommends: yes
  become: yes
  environment:
    DEBIAN_FRONTEND: noninteractive

- name: Set LightDM as default display manager
  debconf:
    name: lightdm
    question: shared/default-x-display-manager
    value: lightdm
    vtype: select
  become: yes
