---
- name: Validate desktop environment choice
  ansible.builtin.assert:
    that:
      - de_environment in de_packages.keys() or de_hyprland_enabled or de_sway_enabled or de_i3_enabled
    fail_msg: >
      Invalid desktop environment: {{ de_environment }}.
      Valid options are: {{ de_packages.keys() | join(', ') }} or enable a window manager
  tags: always

- name: Install desktop environment
  ansible.builtin.include_tasks: "install-{{ de_environment }}.yml"
  when: de_environment in de_packages.keys()
  tags: ['install']

- name: Install Hyprland window manager
  ansible.builtin.include_tasks: "install-hyprland.yml"
  when: de_hyprland_enabled | default(false)
  tags: ['install', 'window-manager']

- name: Install common desktop packages
  ansible.builtin.apt:
    name: "{{ de_common_packages }}"
    state: present
  become: yes
  tags: ['packages']

- name: Configure display manager
  ansible.builtin.include_tasks: display-manager.yml
  tags: ['display-manager']

- name: Configure desktop settings
  ansible.builtin.include_tasks: settings.yml
  when: de_configure_theme or de_configure_display or de_configure_power
  tags: ['settings']

- name: Configure user desktop
  ansible.builtin.include_tasks: user-config.yml
  tags: ['user-config']
