---
# Install communication applications

- name: Install Slack
  snap:
    name: slack
    state: present
  become: yes
  when: "'slack' in communication_apps and enable_snap | default(true)"

- name: Install Discord
  block:
    - name: Download Discord .deb package
      ansible.builtin.get_url:
        url: "https://discord.com/api/download?platform=linux&format=deb"
        dest: /tmp/discord.deb
        mode: '0644'
      become: yes

    - name: Install Discord
      ansible.builtin.apt:
        deb: /tmp/discord.deb
        state: present
      become: yes

    - name: Clean up Discord package
      ansible.builtin.file:
        path: /tmp/discord.deb
        state: absent
      become: yes
  when: "'discord' in communication_apps"

- name: Install Microsoft Teams
  snap:
    name: teams-for-linux
    state: present
  become: yes
  when: "'teams' in communication_apps and enable_snap | default(true)"

- name: Install Zoom
  block:
    - name: Download Zoom .deb package
      ansible.builtin.get_url:
        url: "https://zoom.us/client/latest/zoom_amd64.deb"
        dest: /tmp/zoom_amd64.deb
        mode: '0644'
      become: yes

    - name: Install Zoom
      ansible.builtin.apt:
        deb: /tmp/zoom_amd64.deb
        state: present
      become: yes

    - name: Clean up Zoom package
      ansible.builtin.file:
        path: /tmp/zoom_amd64.deb
        state: absent
      become: yes
  when: "'zoom' in communication_apps"

- name: Install Signal Desktop
  block:
    - name: Create keyring directory
      ansible.builtin.file:
        path: /usr/share/keyrings
        state: directory
        mode: '0755'
      become: yes

    - name: Download Signal GPG key
      ansible.builtin.get_url:
        url: https://updates.signal.org/desktop/apt/keys.asc
        dest: /tmp/signal.asc
      become: yes

    - name: Convert and install Signal GPG key
      ansible.builtin.shell: |
        gpg --dearmor < /tmp/signal.asc > /usr/share/keyrings/signal.gpg
        chmod 644 /usr/share/keyrings/signal.gpg
      args:
        creates: /usr/share/keyrings/signal.gpg
      become: yes

    - name: Add Signal repository with signed-by
      apt_repository:
        repo: >-
          deb [signed-by=/usr/share/keyrings/signal.gpg arch=amd64]
          https://updates.signal.org/desktop/apt xenial main
        state: present
        filename: signal-xenial
      become: yes

    - name: Install Signal
      ansible.builtin.apt:
        name: signal-desktop
        state: present
        update_cache: yes
      become: yes
  when: "'signal' in communication_apps"

- name: Install Telegram Desktop
  ansible.builtin.apt:
    name: telegram-desktop
    state: present
  become: yes
  when: "'telegram' in communication_apps"
