---
- name: Install GNOME theme dependencies
  ansible.builtin.apt:
    name:
      - gnome-tweaks
      - gnome-shell-extensions
      - sassc
      - libglib2.0-dev-bin
    state: present
  become: yes

- name: Clone theme repository for GNOME
  ansible.builtin.git:
    repo: "{{ themes_sources[themes_global_theme].gtk }}"
    dest: "/tmp/{{ themes_global_theme }}-gtk"
    version: main
  when: themes_global_theme in themes_sources

- name: Install GTK theme
  ansible.builtin.shell: |
    cd /tmp/{{ themes_global_theme }}-gtk
    if [ -f install.sh ]; then
      ./install.sh
    elif [ -f INSTALL.md ]; then
      # Manual installation steps based on theme
      case "{{ themes_global_theme }}" in
        dracula)
          cp -r gtk /usr/share/themes/Dracula/
          ;;
        catppuccin)
          cp -r themes/Catppuccin-* /usr/share/themes/
          ;;
        *)
          cp -r * /usr/share/themes/
          ;;
      esac
    fi
  become: yes
  when: themes_global_theme in themes_sources
  changed_when: true

- name: Set GNOME theme
  community.general.dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
  become: yes
  become_user: "{{ primary_user }}"
  loop:
    - { key: "/org/gnome/desktop/interface/gtk-theme", value: "'{{ themes_global_theme | capitalize }}'" }
    - { key: "/org/gnome/desktop/interface/color-scheme", value: "'prefer-dark'" }
    - { key: "/org/gnome/shell/extensions/user-theme/name", value: "'{{ themes_global_theme | capitalize }}'" }
  when: themes_global_theme != 'none'

- name: Set GNOME to dark mode
  community.general.dconf:
    key: "/org/gnome/desktop/interface/color-scheme"
    value: "'prefer-dark'"
    state: present
  become: yes
  become_user: "{{ primary_user }}"
  when: themes_mode == 'dark'
