---
# Git customizations

- name: Configure Git global settings
  community.general.git_config:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    scope: global
  become: yes
  become_user: "{{ primary_user }}"
  loop: "{{ git_global_config }}"
  when: git_global_config is defined

- name: Configure Git aliases
  community.general.git_config:
    name: "alias.{{ item.name }}"
    value: "{{ item.value }}"
    scope: global
  become: yes
  become_user: "{{ primary_user }}"
  loop: "{{ git_aliases }}"
  when: git_aliases is defined

- name: Setup Git user information
  community.general.git_config:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    scope: global
  become: yes
  become_user: "{{ primary_user }}"
  loop:
    - name: user.name
      value: "{{ git_user_name | default('Your Name') }}"
    - name: user.email
      value: "{{ git_user_email | default('your.email@example.com') }}"
  when: git_user_name is defined or git_user_email is defined

- name: Configure Git commit signing
  community.general.git_config:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    scope: global
  become: yes
  become_user: "{{ primary_user }}"
  loop:
    - name: commit.gpgsign
      value: "true"
    - name: user.signingkey
      value: "{{ git_signing_key }}"
  when: git_signing_key is defined

- name: Create global Git ignore file
  ansible.builtin.template:
    src: gitignore_global.j2
    dest: "/home/{{ primary_user }}/.gitignore_global"
    owner: "{{ primary_user }}"
    group: "{{ primary_user }}"
    mode: '0644'
  become: yes

- name: Configure global Git ignore
  community.general.git_config:
    name: core.excludesfile
    value: "/home/{{ primary_user }}/.gitignore_global"
    scope: global
  become: yes
  become_user: "{{ primary_user }}"

- name: Configure Git credential helper
  community.general.git_config:
    name: credential.helper
    value: "cache --timeout=3600"
    scope: global
  become: yes
  become_user: "{{ primary_user }}"
