---
# Install password cracking and analysis tools

# John the Ripper from official repository
- name: Add John the Ripper PPA
  apt_repository:
    repo: "ppa:openwall/john"
    state: present
  become: yes
  when: "'john' in sectools_password_tools and ansible_distribution_version is version('22.04', '>=')"

- name: Install John the Ripper
  ansible.builtin.apt:
    name:
      - john
      - john-data
    state: present
    update_cache: yes
  become: yes
  when: "'john' in sectools_password_tools"

# Hashcat from official repository
- name: Install Hashcat
  ansible.builtin.apt:
    name:
      - hashcat
      - hashcat-data
      - hashcat-nvidia  # NVIDIA GPU support
      - hashid          # Hash identifier
    state: present
  become: yes
  when: "'hashcat' in sectools_password_tools"

# Install hashcat-utils from GitHub
- name: Clone hashcat-utils
  ansible.builtin.git:
    repo: https://github.com/hashcat/hashcat-utils.git
    dest: /opt/hashcat-utils
    version: master
  become: yes
  when: "'hashcat' in sectools_password_tools"

- name: Build hashcat-utils
  ansible.builtin.shell: |
    cd /opt/hashcat-utils/src
    make
  become: yes
  when: "'hashcat' in sectools_password_tools"
  args:
    creates: /opt/hashcat-utils/src/cap2hccapx.bin
  changed_when: true

- name: Install hashcat-utils binaries
  ansible.builtin.shell: |
    cd /opt/hashcat-utils/src
    cp *.bin /usr/local/bin/
    chmod +x /usr/local/bin/*.bin
  become: yes
  when: "'hashcat' in sectools_password_tools"
  changed_when: true

# Hydra from official repository
- name: Install THC-Hydra
  ansible.builtin.apt:
    name:
      - hydra
      - hydra-gtk     # GUI version
    state: present
  become: yes
  when: "'hydra' in sectools_password_tools"

# Medusa
- name: Install Medusa
  ansible.builtin.apt:
    name: medusa
    state: present
  become: yes
  when: "'medusa' in sectools_password_tools"

# Ophcrack with GUI
- name: Install Ophcrack
  ansible.builtin.apt:
    name:
      - ophcrack
      - ophcrack-cli
    state: present
  become: yes
  when: "'ophcrack' in sectools_password_tools"

# Download Ophcrack tables
- name: Create Ophcrack tables directory
  ansible.builtin.file:
    path: /usr/share/ophcrack/tables
    state: directory
    mode: '0755'
  become: yes
  when: "'ophcrack' in sectools_password_tools"

# RainbowCrack
- name: Download RainbowCrack
  ansible.builtin.get_url:
    url: "http://project-rainbowcrack.com/rainbowcrack-1.8-linux64.zip"
    dest: /tmp/rainbowcrack.zip
    mode: '0644'
  become: yes
  when: "'rainbowcrack' in sectools_password_tools"
  failed_when: false

- name: Extract RainbowCrack
  ansible.builtin.unarchive:
    src: /tmp/rainbowcrack.zip
    dest: /opt/
    remote_src: yes
    owner: root
    group: root
  become: yes
  when: "'rainbowcrack' in sectools_password_tools"
  failed_when: false

# Additional password tools
- name: Install additional password cracking tools
  ansible.builtin.apt:
    name:
      - crunch        # Wordlist generator
      - cewl          # Custom wordlist generator
      - rsmangler     # Wordlist mangler
      - statsprocessor # Word generator based on statistics
      - maskprocessor # High-performance word generator
      - princeprocessor # PRINCE attack processor
      - policygen     # Password policy generator
      - pack          # Password analysis and cracking kit
      - patator       # Multi-purpose brute-forcer
      - thc-pptp-bruter  # PPTP brute forcer
      - crowbar       # Brute forcing tool
      - brutespray    # Service brute forcer
    state: present
  become: yes
  failed_when: false

# SecLists wordlists from GitHub
- name: Clone SecLists repository
  ansible.builtin.git:
    repo: https://github.com/danielmiessler/SecLists.git
    dest: /usr/share/seclists
    version: master
    depth: 1  # Shallow clone to save space
  become: yes

# Create wordlist directory structure
- name: Create wordlist directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  become: yes
  loop:
    - /usr/share/wordlists
    - /usr/share/wordlists/passwords
    - /usr/share/wordlists/usernames
    - /usr/share/wordlists/discovery

# Link common wordlists
- name: Link rockyou wordlist
  ansible.builtin.file:
    src: /usr/share/seclists/Passwords/Leaked-Databases/rockyou.txt
    dest: /usr/share/wordlists/rockyou.txt
    state: link
  become: yes
  failed_when: false

# Install password analysis tools
- name: Install password analysis tools
  ansible.builtin.pip:
    name:
      - passlib       # Password hashing library
      - hashID        # Hash identifier
      - name-that-hash # Modern hash identifier
    state: present
    executable: pip3
  become: yes

# Hashview (GUI for password cracking)
- name: Install Hashview dependencies
  ansible.builtin.apt:
    name:
      - ruby-full
      - ruby-dev
      - libmysqlclient-dev
      - redis-server
      - mysql-server
    state: present
  become: yes
  when: "'hashview' in sectools_password_tools"

# Install Johnny (GUI for John the Ripper)
- name: Install Johnny GUI
  ansible.builtin.apt:
    name: johnny
    state: present
  become: yes
  when: "'john' in sectools_password_tools"
  failed_when: false
