---
- name: Include OS-specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
        - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "default.yml"
      paths:
        - "../vars"
      skip: true
  tags: always

- name: Fix APT issues first
  ansible.builtin.include_tasks: apt-cleanup.yml
  tags: ['apt-cleanup', 'repositories', 'apt']
  when: fix_apt_issues | default(true)

- name: Configure APT repositories
  ansible.builtin.include_tasks: repositories.yml
  tags: ['repositories', 'apt']

- name: Install base packages
  ansible.builtin.include_tasks: packages.yml
  tags: ['packages']

- name: Configure system
  ansible.builtin.include_tasks: system.yml
  tags: ['system']

- name: Configure user
  ansible.builtin.include_tasks: user.yml
  when: common_configure_user
  tags: ['user']

- name: Configure performance settings
  ansible.builtin.include_tasks: performance.yml
  tags: ['performance']
