---
- name: Upgrade all packages
  ansible.builtin.apt:
    upgrade: dist
    autoclean: yes
    autoremove: yes
  become: yes
  tags: ['upgrade']

- name: Install base system packages
  ansible.builtin.apt:
    name: "{{ common_base_packages }}"
    state: present
  become: yes

- name: Install additional essential packages
  ansible.builtin.apt:
    name: "{{ essential_packages }}"
    state: present
  become: yes
  when: essential_packages is defined

- name: Remove unnecessary packages
  ansible.builtin.apt:
    autoclean: yes
    autoremove: yes
  become: yes
