---
galaxy_info:
  author: bootstrap-ubuntu
  description: Desktop Environment setup for Ubuntu (GNOME, KDE, XFCE, etc.)
  license: MIT
  min_ansible_version: "2.12"
  platforms:
    - name: Ubuntu
      versions:
        - focal    # 20.04
        - jammy    # 22.04
        - noble    # 24.04
  galaxy_tags:
    - ubuntu
    - desktop
    - gnome
    - kde
    - xfce

dependencies:
  - role: common
